### ISSUE TITLE
method to keep up to date?

### ISSUE THREAD

**Issue by cablehead** [demurgos/mime_classifier#1]
1/ thank you for making this available standalone

2/ would you be interested trying to track this crate with updates in the main servo repo? I'd be able to spend sometime to help with that.

**Comment by demurgos** [comment]
Hello :wave: 
The best would be if Servo took over this crate and published it directly.
I did not need updates personally from Servo so I did not keep a close eye on their impl. Remaining up-to-date would be great. What do you propose?

**Comment by cablehead** [comment]
> The best would be if Servo took over this crate and published it directly.

Totally

> What do you propose?

Thank you for being responsive. Perhaps if Servo doesn't pick it up and some useful updates appear upstream, I could do the leg work to transfer the updates to this repo?

**Comment by demurgos** [comment]
Apparently there's already an open discussion about it: https://github.com/servo/servo/discussions/33415

I don't have much time to refactor the servo repo to extract the crate currently. If you want to do it, you can probably submit a PR to them and I'll handle the crates.io permissions. I can do it myself some time later, but prefer to avoid giving a deadline.

**Comment by cablehead** [comment]
it looks like the core team doesn't have the bandwidth to take it on either. they did confirm the version you're hosting is still up to date 

> the code hasn't been modified since the crate was published

and its been 2 years now, so even left as-is this is a great service to the community. i'll try and keep an eye out now again to see if the official version ever updates..

thanks so much for making this available standalone @demurgos 🙏
